@echo off
del *.aux > nul
del *.bbl > nul
del *.bcf > nul
del *-blx.bib > nul
del *.blg > nul
del *.idx > nul
del *.ilg > nul
del *.ind > nul
del *.lof > nul
del *.log > nul
del *.lol > nul
del *.nlo > nul
del *.out > nul
del *.xml > nul
del *.synctex  > nul
del *.toc > nul
del *.tps > nul
del content\*.aux > nul
del content\*.log > nul
del formal\*.aux > nul
del formal\*.log > nul
del formal\htwg\*.aux > nul
del formal\htwg\*.log > nul
del formal\hsrw\*.aux > nul
del formal\hsrw\*.log > nul
del praeambel\*.aux > nul
del praeambel\*.log > nul